// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Test","status":true,"description":"Creates and spawns an NPC on the map using specified parameters.","parameters":{}}
];
