// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"helloWorld","status":true,"description":"This is a Hello World plugin.","parameters":{}},
{"name":"npcUtils","status":true,"description":"This is a demo plugin.","parameters":{}},
{"name":"GALV_EventSpawnerMZ","status":true,"description":"(v.1.2) Spawn events from a specified spawn map to a desired location.","parameters":{"mId":"2"}}
];
